### ISSUE TITLE
Supervised classifier from older version

### ISSUE THREAD

**Issue by lauren546** [DrCoffey/DeepSqueak#175] opened 2022-07-27 19:10 UTC
Hi Dr. Coffey! I am attempting to use a supervised classifier that was trained on an older version of DeepSqueak in the newest version, but I am experiencing error messages. Is there any way to use the old classifier that was already trained? 

I also cannot seem to train a new classifier, even when using labeled detection files from the current version. I get the following error after going to Train Supervised Classifier and choosing detection files:
"Dot indexing is not supported for variables of this type.

Error in SupervisedClassification_Callback (line 29)
wind=options.spectrogram.windowsize;

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in DeepSqueak (line 29)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('SupervisedClassification_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating Menu Callback."

 
I would appreciate any help, thank you.

**Comment by DrCoffey** [comment] 2022-07-27 19:45
Hey @lauren546. You can't use the old classifier because the image generation has changed. I know what the problem is with the new version and will have it fixed in a few minutes.

**Comment by DrCoffey** [comment] 2022-07-27 19:54
Hey @lauren546, if you update DeepSqueak supervised classification should be all fixed. Re-open the issue if you are still having a problem.

**Closed by DrCoffey** 2022-07-27 19:54 UTC
